"""add adopters and pets

Revision ID: f48b5da0666a
Revises: 
Create Date: 2018-05-31 18:12:22.181140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48b5da0666a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adopters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('update_at', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('age', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), server_default=sa.text("'0'"), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('update_at', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('age', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('adopters')
    # ### end Alembic commands ###
